spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5b3c8931560d04387997
            client-secret : 5e6b461f457ef757c6df42a68d40bd172a1a8fe1
            scope: name,email,avatar_url